# Generated by Django 4.1.3 on 2022-12-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=30)),
                ('photo', models.FilePathField()),
                ('price', models.IntegerField()),
                ('descriptions', models.CharField(max_length=150)),
            ],
        ),
    ]
