# Generated by Django 4.1.3 on 2022-12-23 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_alter_products_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_Product', models.CharField(max_length=30)),
                ('order_Price', models.PositiveIntegerField()),
                ('order_Quantity', models.PositiveIntegerField()),
                ('ordeer_Global_Summa', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.ImageField(upload_to='file/images'),
        ),
        migrations.CreateModel(
            name='OrderPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('GlobalSumma', models.PositiveIntegerField()),
                ('ProductsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.order_products')),
            ],
        ),
        migrations.AddField(
            model_name='order_products',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.products'),
        ),
    ]
