# Generated by Django 4.1.3 on 2022-12-23 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_remove_orderperson_productsid_products_quantityprod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='quantityProd',
        ),
        migrations.RemoveField(
            model_name='products',
            name='summa',
        ),
    ]
